### ISSUE TITLE
Issue with the code

### ISSUE THREAD

**Issue by JohnMos** [darkarp/chrome-password-hacking#1]
File "create_server.py", line 2, in <module>
import os, sys, cgi, py2exe, BaseHTPPServer, sqlite3 , win32crypt
ImportError: DLL load failer: The specified module could not be found.
Any idea?

**Comment by darkarp** [comment]
Looks like you're missing something in your %PATH% variable. What is currently your %PATH% environment variable?

**Comment by JohnMos** [comment]
same problem, after the powershell command...

**Comment by darkarp** [comment]
Have you downloaded the 32 bit version?

**Comment by JohnMos** [comment]
no i have 64-bit

**Comment by darkarp** [comment]
You have to download the 32bit version. You have to make sure both py2exe and python are 32 bit. Everything has to be in 32 bit. Don't worry if you have 64 bit Windows, it will still work.

**Comment by darkarp** [comment]
That error happens because you installed the 64 bit version of python. You should install the 32 bit

**Comment by JohnMos** [comment]
everything is ok now.. Thank you very much, trying to find port forwarding 80 and 8080

**Comment by darkarp** [comment]
Okay! There are many tutorials on how to do that. Let me just say that if you didn't change anything on the scripts, port forwarding port 80 is enough :)

Basically what you want to do is the following: 
1. Go to your router admin page: 192.168.1.1 or 192.168.0.1, depending on your router could be different (you can check that using the ipconfig command and checking the default gateway). 
2. Look for LAN/WAN/Network settings, or something like this, and then Port Forwarding. Here you want to include your LOCAL ip address (ipconfig again) and type port 80 (both external and internal).  
3. You're done. If you can't find it just do a google search or maybe even google your router brand as well.
