### ISSUE TITLE
ImportError: DLL load failer: The specified module could not be found.

### ISSUE THREAD

**Issue by bowser0000** [darkarp/chrome-password-hacking#3]
File "C:\Users\\\*****\Desktop\chrome-password-hacking-master\create_server.py", line 3, in <module>
    import os, sys, cgi, py2exe, BaseHTTPServer, sqlite3, win32crypt
ImportError: DLL load failed: The specified module could not be found.

I have tried running the powershell command, and have installed python 2.7 in 32 bit and everything else in 32 bit. Not sure why it still doesn't work.

**Comment by darkarp** [comment]
Are you sure you are running it with the 32-bit version of python? Try to run it giving the full executable path so in cmd: `C:\Python27\python.exe create_server.py`

**Comment by bowser0000** [comment]
I only have 2.7 32-bit installed, and the full path in cmd still shows the same error :\

**Comment by darkarp** [comment]
That is indeed strange. Did you install python in the default directory, as in, C:\Python27 ?

**Comment by bowser0000** [comment]
Yes I have https://i.imgur.com/M1FKgOa.png

**Comment by darkarp** [comment]
Have you tried to restart your computer and trying again? I'm trying to reproduce the error so that I can be of assistance but I'm not being able to

**Comment by bowser0000** [comment]
I have tried restarting my computer and reinstalling Python but none of those have fixed it.

**Comment by darkarp** [comment]
I'll continue to try to reproduce the error. In the meantime, you might want to search for people with a similar problem, since it isn't a problem with the code itself.

**Comment by darkarp** [comment]
Apparently, I tried to have a second perspective on this issue but the only conclusion is that you're missing a required DLL. The easiest way to verify this is just by installing VirtualBox (or another Virtualization software of your choice), installing windows, updating, repeating all the instructions and trying it there.

**Comment by bowser0000** [comment]
Just tried it in a VM

https://i.imgur.com/GYn5Ved.png

**Comment by darkarp** [comment]
Okay. Try the following, place all the files belonging to the code in a folder in C:\ Directory, like C:\ChromePasswords

Then, try to run create_server.py again

**Comment by bowser0000** [comment]
Traceback (most recent call last):
  File "C:\ChromePasswords\create_server.py", line 48, in <module>
    with open('create_server.py') as f1:
IOError: [Errno 2] No such file or directory: 'create_server.py'

**Comment by darkarp** [comment]
That is most certainly weird. Basically that line of the code is opening the same file you're running but it's saying that it doesn't exist. 

Try this: Add this line before line 48: 
`os.chdir(r'C:\ChromePasswords')`

And then change line 52 to:
`i = 60`

Then save and try again. If this doesn't work, to be honest the only way I can think to help you is to enter in a remote connection to your VM to see what I can do, because I'm not quite sure how to fix that.

**Comment by bowser0000** [comment]
It works now, thanks for your help!

**Comment by darkarp** [comment]
No problem
