### ISSUE TITLE
Is there macOs alternative?

### ISSUE THREAD

**Issue by keevvinc** [darkarp/chrome-password-hacking#4]
As someone mentioned on Reddit, I would like to by-pass the popup dialog

**Comment by darkarp** [comment]
I will work on it after all my exams. I'll note this as an Enhancement

**Comment by darkarp** [comment]
I was going to start working on a Mac version when I found out that another developer is working on a tookit that includes this functionality for Mac OS, which is why I decided not to pursue this and instead share his work with you: 
https://github.com/Marten4n6/EvilOSX
