### ISSUE TITLE
I don't receive the email.

### ISSUE THREAD

**Issue by newestmindcoder** [darkarp/chrome-password-hacking#8]
I'm somewhat new to python and learning online. When I try it on my own PC I get this error 
**Traceback (most recent call last):
  File "server.py", line 97, in <module>
  File "server.py", line 38, in getpass
  File "shutil.pyo", line 82, in copyfile
IOError: [Errno 2] No such file or directory: 'C:\\\\Users\\DELL\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Login Data'**
I'm stuck here. I could use your help. Thanks in advance.

**Comment by darkarp** [comment]
Oh that may be a little typo on the code, I'll check it out.

**Comment by darkarp** [comment]
Please download the source code again and see if it works now :) 
(btw download the source code, not the release)

**Comment by newestmindcoder** [comment]
Hi thanks for your response and time, still no email and here's what I get in the log now
**Traceback (most recent call last):
  File "server.py", line 99, in <module>
  File "server.py", line 42, in getpass
sqlite3.OperationalError: unable to open database file**

**Comment by darkarp** [comment]
hmm, let me try to change it once more, I believe this will fix your error. I'll notify you once it's been changed.

**Comment by newestmindcoder** [comment]
Okay done, the server.py is in the zip file. Thanks.
[server.zip](https://github.com/darkarp/chrome-password-hacking/files/2950357/server.zip)

**Comment by darkarp** [comment]
Thanks. I'm trying to replicate the error, but I am not being able to do so. It's working perfectly well for me.
May I ask you if you username in the pc uses any special characters?

**Comment by newestmindcoder** [comment]
No it doesn't. I'll try doing it again from scratch.

**Comment by darkarp** [comment]
Is it working for you?

**Comment by newestmindcoder** [comment]
No not yet, I'm still trying though. Looking to see if I'll use another PC

**Comment by darkarp** [comment]
Did it work?

**Comment by darkarp** [comment]
Closing due to lack of response
